### ISSUE TITLE
Receive an error when running script

### ISSUE THREAD

**Issue by angieconde** [SohaibAjmal/Okta-UD-Scripts#1]
Hi there,

When I run this, I receive the following response, any idea why? 

C:\Python27\Scripts\Okta>get_all_active_users.py
Traceback (most recent call last):
  File "C:\Python27\Scripts\Okta\get_all_active_users.py", line 104, in <module>
    DownloadSFUsers()
  File "C:\Python27\Scripts\Okta\get_all_active_users.py", line 99, in DownloadSFUsers
    writer.writerow([firstName,lastName,email,login])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

**Comment by angieconde** [comment]
Nevermind - solved it by adding this:

import sys
reload(sys)
sys.setdefaultencoding('utf8')
