### ISSUE TITLE
script errors

### ISSUE THREAD

**Issue by plasticarmyman1** [SohaibAjmal/Okta-UD-Scripts#2]
You need to update the scripts, there are syntax errors with the print command and then I am getting an error here:

C:\Scripts>python delete_users.py
Traceback (most recent call last):
  File "C:\Scripts\delete_users.py", line 177, in <module>
    DeleteUsers()
  File "C:\Scripts\delete_users.py", line 109, in DeleteUsers
    deactiveWriter.writerow(["firstName", "lastName", "email", "login", "status"])
TypeError: a bytes-like object is required, not 'str'

**Comment by gabrielsroka** [comment]
the script was written for Python 2 (which is no longer supported).

you can try running it in Python 2 or port it to Python 3. 

if you want to try it with Python 3, a simple change to start with is to replace all the `print` statements with the `print()` function. so change:
`print 'hello'`
to
`print('hello')`

other changes might be necessary, too

**Comment by plasticarmyman1** [comment]
> 

Can you update these scripts to run under a secure version of python?
We have no way to bulk delete users other than to use broken scripts...let me correct myself...we have no way to bulk delete users.....this is a bit ridiculous...i have been wrestling with this for days and I just want to do something simple that pretty much any other user management tool has

**Comment by gabrielsroka** [comment]
give this a try. i changed the `print` statements as i wrote above, changed the `open` from `wb` to `w`, and removed some extra stuff

```python
import requests
import json
import csv


orgName = "org-domain.oktapreview"
apiKey = ""

api_token = "SSWS "+ apiKey

headers = {'Accept':'application/json','Content-Type':'application/json','Authorization':api_token}

   

def GetPaginatedResponse(url):

    response = requests.request("GET", url, headers=headers)

    returnResponseList = []

    responseJSON = json.dumps(response.json())

    responseList = json.loads(responseJSON)

    returnResponseList = returnResponseList + responseList


    if "errorCode" in responseJSON:

        print("\nYou encountered following Error: \n")
        print(responseJSON)
        print("\n")

        return "Error"

    else:

        headerLink= response.headers["Link"]
  
        while str(headerLink).find("rel=\"next\"") > -1:

            linkItems = str(headerLink).split(",")

            nextCursorLink = ""
            for link in linkItems:

                if str(link).find("rel=\"next\"") > -1:
                    nextCursorLink = str(link)


            nextLink = str(nextCursorLink.split(";")[0]).strip()
            nextLink = nextLink[1:]
            nextLink = nextLink[:-1]

            url = nextLink

            response = requests.request("GET", url, headers=headers)

            responseJSON = json.dumps(response.json())

            responseList = json.loads(responseJSON)

            returnResponseList = returnResponseList + responseList
        
            headerLink= response.headers["Link"]

        
        returnJSON = json.dumps(returnResponseList)

        return returnResponseList



def DELETERequest(url):

    response = requests.delete(url, headers=headers)

    responseJSON = response

    if "errorCode" in responseJSON:
        print("\nYou encountered following Error: \n")
        print(responseJSON)
        print("\n")

        return "Error"

    else:

        return responseJSON


def DeleteUsers():


    ##### CSV Files #####

     # Deactive Users
    deactiveUsers = open("Deactive-Users.csv", "w")

    deactiveWriter = csv.writer(deactiveUsers)
    
    deactiveWriter.writerow(["firstName", "lastName", "email", "login", "status"])

    #Deleted Users
    deletedUsers = open("Deleted-Users.csv", "w")

    deletedWriter = csv.writer(deletedUsers)
    
    deletedWriter.writerow(["firstName", "lastName", "email", "login", "status"])

     #Not Deleted Users
    notDeletedUsers = open("Not-Deleted-Users.csv", "w")

    notDeletedWriter = csv.writer(notDeletedUsers)
    
    notDeletedWriter.writerow(["firstName", "lastName", "login", "error"])

    ##### CSV Files #####

    url = "https://"+orgName+".com/api/v1/users?filter=status eq \"DEPROVISIONED\""

    deactivedUsers = GetPaginatedResponse(url)

    deactivedUsersCount = 0
    deletedUsersCount = 0
    notDeletedUserCount = 0

    for user in deactivedUsers:

        userId = str(user["id"])

        deleteUrl = "https://"+orgName+".com/api/v1/users/"+userId

        deactiveWriter.writerow([user["profile"]["firstName"], user["profile"]["lastName"], user["profile"]["email"], user["profile"]["login"], user["status"]])
        deactivedUsersCount += 1

        response = DELETERequest(deleteUrl)

        response = str(response)

        if response == "<Response [204]>":

            print(str(user["profile"]["login"]) + " is Deleted" )
            deletedUsersCount += 1

            deletedWriter.writerow([user["profile"]["firstName"], user["profile"]["lastName"], user["profile"]["email"], user["profile"]["login"], user["status"]])
        
        else:

            notDeletedUserCount += 1

            notDeletedWriter.writerow([user["profile"]["firstName"], user["profile"]["lastName"], user["profile"]["login"], response])
    


    print("Deactivated Users: " + str(deactivedUsersCount))
    print("Deleted Users: " + str(deletedUsersCount))
    print("Not Deleted Users: " + str(notDeletedUserCount))

   

  

        

if __name__ == "__main__":

	DeleteUsers()
```

**Comment by plasticarmyman1** [comment]
That seems to be working now, thank you very much

**Comment by gabrielsroka** [comment]
you're welcome. please close the issue when you're ready
